### ISSUE TITLE
基本没打成功过

### ISSUE THREAD

**Issue by hopeabcd** [abc123info/EquationToolsGUI#2]

**Comment by abc123info** [comment]
需要选择目标操作系统，提前选择好。

**Comment by abc123info** [comment]
如果有360防护等等，dll做免杀或者默认是没办法打成功的。

**Comment by hopeabcd** [comment]
按着提示来着的，x64版本直接注入lsass进程获得system权限，x32版本注入explore进程(或wlms.exe)，自己也搭过试试，用msf就能成功




立即改变
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "abc123info/EquationToolsGUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 晚上11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [abc123info/EquationToolsGUI] 基本没打成功过 (Issue #2)





 
需要选择目标操作系统，进行很多设置，提前选择好。
